project_id = "zbrscuoqmkdbmdimdnqu"

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-location-density]
verify_jwt = true

[functions.check-geofence]
verify_jwt = true

[functions.scrape-venue-images]
verify_jwt = true

[functions.generate-deal-image]
verify_jwt = false
