project_id = "zbrscuoqmkdbmdimdnqu"

[functions.get-mapbox-token]
verify_jwt = true

[functions.get-location-density]
verify_jwt = true

[functions.get-google-places-data]
verify_jwt = true

[functions.search-google-places-venues]
verify_jwt = true

[functions.check-geofence]
verify_jwt = true

[functions.scrape-venue-images]
verify_jwt = true

[functions.generate-deal-image]
verify_jwt = true

[functions.get-mixpanel-analytics]
verify_jwt = true

[functions.remove-image-watermark]
verify_jwt = false
